// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, name, key_hash, key_suffix)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, key_hash, key_suffix, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	KeyHash   string      `json:"key_hash"`
	KeySuffix string      `json:"key_suffix"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.KeyHash,
		arg.KeySuffix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeySuffix,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND project_id = $2
`

type DeleteAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.ProjectID)
	return err
}

const getAPIKeyBySuffix = `-- name: GetAPIKeyBySuffix :one
SELECT id, project_id, key_hash FROM api_keys WHERE key_suffix = $1
`

type GetAPIKeyBySuffixRow struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	KeyHash   string      `json:"key_hash"`
}

func (q *Queries) GetAPIKeyBySuffix(ctx context.Context, keySuffix string) (GetAPIKeyBySuffixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyBySuffix, keySuffix)
	var i GetAPIKeyBySuffixRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.KeyHash)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_suffix, created_at, last_used_at 
FROM api_keys 
WHERE project_id = $1 ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	KeySuffix  string             `json:"key_suffix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, projectID pgtype.UUID) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeySuffix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
