// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cloneAssets = `-- name: CloneAssets :exec
INSERT INTO assets (
    update_id,
    platform,
    file_name,
    mime_type,
    key,
    url,
    file_hash,
    hash,
    storage_provider
)
SELECT $1,
    a.platform,
    a.file_name,
    a.mime_type,
    a.key,
    a.url,
    a.file_hash,
    a.hash,
    a.storage_provider
FROM assets a
WHERE a.update_id = $2
`

type CloneAssetsParams struct {
	TargetUpdateID pgtype.UUID `json:"target_update_id"`
	SourceUpdateID pgtype.UUID `json:"source_update_id"`
}

func (q *Queries) CloneAssets(ctx context.Context, arg CloneAssetsParams) error {
	_, err := q.db.Exec(ctx, cloneAssets, arg.TargetUpdateID, arg.SourceUpdateID)
	return err
}

const countOtherAssetReferences = `-- name: CountOtherAssetReferences :one
SELECT COUNT(*) FROM assets
WHERE key = $1 AND update_id != $2
`

type CountOtherAssetReferencesParams struct {
	Key      string      `json:"key"`
	UpdateID pgtype.UUID `json:"update_id"`
}

func (q *Queries) CountOtherAssetReferences(ctx context.Context, arg CountOtherAssetReferencesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherAssetReferences, arg.Key, arg.UpdateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (
    update_id,
    platform,
    file_name,
    mime_type,
    key,
    url,
    file_hash,
    hash,
    storage_provider
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAssetParams struct {
	UpdateID        pgtype.UUID `json:"update_id"`
	Platform        string      `json:"platform"`
	FileName        string      `json:"file_name"`
	MimeType        string      `json:"mime_type"`
	Key             string      `json:"key"`
	Url             string      `json:"url"`
	FileHash        string      `json:"file_hash"`
	Hash            string      `json:"hash"`
	StorageProvider string      `json:"storage_provider"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.Exec(ctx, createAsset,
		arg.UpdateID,
		arg.Platform,
		arg.FileName,
		arg.MimeType,
		arg.Key,
		arg.Url,
		arg.FileHash,
		arg.Hash,
		arg.StorageProvider,
	)
	return err
}

const deleteAssetByUpdateID = `-- name: DeleteAssetByUpdateID :exec
DELETE FROM assets WHERE update_id = $1
`

func (q *Queries) DeleteAssetByUpdateID(ctx context.Context, updateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetByUpdateID, updateID)
	return err
}

const deleteAssetByUpdateIDandPlatform = `-- name: DeleteAssetByUpdateIDandPlatform :exec
DELETE FROM assets WHERE update_id = $1 AND platform = $2
`

type DeleteAssetByUpdateIDandPlatformParams struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Platform string      `json:"platform"`
}

func (q *Queries) DeleteAssetByUpdateIDandPlatform(ctx context.Context, arg DeleteAssetByUpdateIDandPlatformParams) error {
	_, err := q.db.Exec(ctx, deleteAssetByUpdateIDandPlatform, arg.UpdateID, arg.Platform)
	return err
}

const getAssetByFileHash = `-- name: GetAssetByFileHash :one
SELECT id, update_id, platform, file_name, mime_type, key, url, file_hash, hash, storage_provider FROM assets WHERE file_hash = $1
`

func (q *Queries) GetAssetByFileHash(ctx context.Context, fileHash string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByFileHash, fileHash)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.Platform,
		&i.FileName,
		&i.MimeType,
		&i.Key,
		&i.Url,
		&i.FileHash,
		&i.Hash,
		&i.StorageProvider,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, update_id, platform, file_name, mime_type, key, url, file_hash, hash, storage_provider FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.Platform,
		&i.FileName,
		&i.MimeType,
		&i.Key,
		&i.Url,
		&i.FileHash,
		&i.Hash,
		&i.StorageProvider,
	)
	return i, err
}

const getAssetsByUpdateID = `-- name: GetAssetsByUpdateID :many
SELECT id, update_id, platform, file_name, mime_type, key, url, file_hash, hash, storage_provider FROM assets 
WHERE update_id = $1
ORDER BY platform, file_name
`

func (q *Queries) GetAssetsByUpdateID(ctx context.Context, updateID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getAssetsByUpdateID, updateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UpdateID,
			&i.Platform,
			&i.FileName,
			&i.MimeType,
			&i.Key,
			&i.Url,
			&i.FileHash,
			&i.Hash,
			&i.StorageProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
