// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownloadEvent = `-- name: CreateDownloadEvent :one
INSERT INTO download_events (
    update_id,
    project_id,
    device_hash,
    platform,
    channel
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, update_id, project_id, timestamp, device_hash, platform, channel
`

type CreateDownloadEventParams struct {
	UpdateID   pgtype.UUID `json:"update_id"`
	ProjectID  pgtype.UUID `json:"project_id"`
	DeviceHash string      `json:"device_hash"`
	Platform   string      `json:"platform"`
	Channel    string      `json:"channel"`
}

func (q *Queries) CreateDownloadEvent(ctx context.Context, arg CreateDownloadEventParams) (DownloadEvent, error) {
	row := q.db.QueryRow(ctx, createDownloadEvent,
		arg.UpdateID,
		arg.ProjectID,
		arg.DeviceHash,
		arg.Platform,
		arg.Channel,
	)
	var i DownloadEvent
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.ProjectID,
		&i.Timestamp,
		&i.DeviceHash,
		&i.Platform,
		&i.Channel,
	)
	return i, err
}

const getGlobalRecentDownloads = `-- name: GetGlobalRecentDownloads :many
SELECT platform, channel, COUNT(*) AS count
FROM download_events
GROUP BY platform, channel
ORDER BY count DESC
`

type GetGlobalRecentDownloadsRow struct {
	Platform string `json:"platform"`
	Channel  string `json:"channel"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetGlobalRecentDownloads(ctx context.Context) ([]GetGlobalRecentDownloadsRow, error) {
	rows, err := q.db.Query(ctx, getGlobalRecentDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalRecentDownloadsRow
	for rows.Next() {
		var i GetGlobalRecentDownloadsRow
		if err := rows.Scan(&i.Platform, &i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDownloadsByProject = `-- name: GetRecentDownloadsByProject :many
SELECT update_id, platform, channel, COUNT(*) AS count
FROM download_events
WHERE project_id = $1
GROUP BY update_id, platform, channel
ORDER BY count DESC
`

type GetRecentDownloadsByProjectRow struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Platform string      `json:"platform"`
	Channel  string      `json:"channel"`
	Count    int64       `json:"count"`
}

func (q *Queries) GetRecentDownloadsByProject(ctx context.Context, projectID pgtype.UUID) ([]GetRecentDownloadsByProjectRow, error) {
	rows, err := q.db.Query(ctx, getRecentDownloadsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentDownloadsByProjectRow
	for rows.Next() {
		var i GetRecentDownloadsByProjectRow
		if err := rows.Scan(
			&i.UpdateID,
			&i.Platform,
			&i.Channel,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
