// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownloadEvent = `-- name: CreateDownloadEvent :one
INSERT INTO download_events (
    update_id,
    project_id,
    device_hash,
    platform,
    channel
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, update_id, project_id, timestamp, device_hash, platform, channel
`

type CreateDownloadEventParams struct {
	UpdateID   pgtype.UUID `json:"update_id"`
	ProjectID  pgtype.UUID `json:"project_id"`
	DeviceHash string      `json:"device_hash"`
	Platform   string      `json:"platform"`
	Channel    string      `json:"channel"`
}

func (q *Queries) CreateDownloadEvent(ctx context.Context, arg CreateDownloadEventParams) (DownloadEvent, error) {
	row := q.db.QueryRow(ctx, createDownloadEvent,
		arg.UpdateID,
		arg.ProjectID,
		arg.DeviceHash,
		arg.Platform,
		arg.Channel,
	)
	var i DownloadEvent
	err := row.Scan(
		&i.ID,
		&i.UpdateID,
		&i.ProjectID,
		&i.Timestamp,
		&i.DeviceHash,
		&i.Platform,
		&i.Channel,
	)
	return i, err
}

const getDownloadsByChannel = `-- name: GetDownloadsByChannel :many
SELECT channel, COUNT(*) as count
FROM download_events
WHERE project_id = $1
GROUP BY channel
ORDER BY count DESC
`

type GetDownloadsByChannelRow struct {
	Channel string `json:"channel"`
	Count   int64  `json:"count"`
}

func (q *Queries) GetDownloadsByChannel(ctx context.Context, projectID pgtype.UUID) ([]GetDownloadsByChannelRow, error) {
	rows, err := q.db.Query(ctx, getDownloadsByChannel, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownloadsByChannelRow
	for rows.Next() {
		var i GetDownloadsByChannelRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadsByPlatform = `-- name: GetDownloadsByPlatform :many
SELECT platform, COUNT(*) as count
FROM download_events
WHERE project_id = $1
GROUP BY platform
ORDER BY count DESC
`

type GetDownloadsByPlatformRow struct {
	Platform string `json:"platform"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetDownloadsByPlatform(ctx context.Context, projectID pgtype.UUID) ([]GetDownloadsByPlatformRow, error) {
	rows, err := q.db.Query(ctx, getDownloadsByPlatform, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownloadsByPlatformRow
	for rows.Next() {
		var i GetDownloadsByPlatformRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadsByUpdate = `-- name: GetDownloadsByUpdate :many
SELECT 
    update_id,
    COUNT(*) as download_count,
    COUNT(DISTINCT device_hash) as unique_devices
FROM download_events
WHERE project_id = $1
GROUP BY update_id
ORDER BY MAX(timestamp) DESC
`

type GetDownloadsByUpdateRow struct {
	UpdateID      pgtype.UUID `json:"update_id"`
	DownloadCount int64       `json:"download_count"`
	UniqueDevices int64       `json:"unique_devices"`
}

func (q *Queries) GetDownloadsByUpdate(ctx context.Context, projectID pgtype.UUID) ([]GetDownloadsByUpdateRow, error) {
	rows, err := q.db.Query(ctx, getDownloadsByUpdate, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownloadsByUpdateRow
	for rows.Next() {
		var i GetDownloadsByUpdateRow
		if err := rows.Scan(&i.UpdateID, &i.DownloadCount, &i.UniqueDevices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalDownloadsByChannel = `-- name: GetGlobalDownloadsByChannel :many
SELECT channel, COUNT(*) as count FROM download_events GROUP BY channel ORDER BY count DESC
`

type GetGlobalDownloadsByChannelRow struct {
	Channel string `json:"channel"`
	Count   int64  `json:"count"`
}

func (q *Queries) GetGlobalDownloadsByChannel(ctx context.Context) ([]GetGlobalDownloadsByChannelRow, error) {
	rows, err := q.db.Query(ctx, getGlobalDownloadsByChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalDownloadsByChannelRow
	for rows.Next() {
		var i GetGlobalDownloadsByChannelRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalDownloadsByPlatform = `-- name: GetGlobalDownloadsByPlatform :many
SELECT platform, COUNT(*) as count FROM download_events GROUP BY platform ORDER BY count DESC
`

type GetGlobalDownloadsByPlatformRow struct {
	Platform string `json:"platform"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetGlobalDownloadsByPlatform(ctx context.Context) ([]GetGlobalDownloadsByPlatformRow, error) {
	rows, err := q.db.Query(ctx, getGlobalDownloadsByPlatform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalDownloadsByPlatformRow
	for rows.Next() {
		var i GetGlobalDownloadsByPlatformRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalRecentDownloads = `-- name: GetGlobalRecentDownloads :one
SELECT COUNT(*) as count FROM download_events WHERE timestamp > $1
`

func (q *Queries) GetGlobalRecentDownloads(ctx context.Context, timestamp pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalRecentDownloads, timestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGlobalTotalDownloads = `-- name: GetGlobalTotalDownloads :one
SELECT COUNT(*) as count FROM download_events
`

func (q *Queries) GetGlobalTotalDownloads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalTotalDownloads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentDownloadsByProject = `-- name: GetRecentDownloadsByProject :one
SELECT COUNT(*) as count
FROM download_events
WHERE project_id = $1
  AND timestamp > $2
`

type GetRecentDownloadsByProjectParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) GetRecentDownloadsByProject(ctx context.Context, arg GetRecentDownloadsByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentDownloadsByProject, arg.ProjectID, arg.Timestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalDownloadsByProject = `-- name: GetTotalDownloadsByProject :one
SELECT COUNT(*) as count
FROM download_events
WHERE project_id = $1
`

func (q *Queries) GetTotalDownloadsByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalDownloadsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
