// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_stats.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateDownloadEvents = `-- name: AggregateDownloadEvents :exec
INSERT INTO download_stats (project_id, update_id, platform, channel, date, download_count)
SELECT 
    project_id, update_id, platform, channel,
    timestamp::date AS date,
    COUNT(*) AS download_count
FROM download_events
WHERE timestamp < $1
GROUP BY project_id, update_id, platform, channel, timestamp::date
ON CONFLICT (project_id, update_id, platform, channel, date)
DO UPDATE SET
    download_count = download_stats.download_count + EXCLUDED.download_count
`

func (q *Queries) AggregateDownloadEvents(ctx context.Context, timestamp pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, aggregateDownloadEvents, timestamp)
	return err
}

const deleteAggregatedEvents = `-- name: DeleteAggregatedEvents :exec
DELETE FROM download_events WHERE timestamp < $1
`

func (q *Queries) DeleteAggregatedEvents(ctx context.Context, timestamp pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAggregatedEvents, timestamp)
	return err
}

const getTotalDownloadStats = `-- name: GetTotalDownloadStats :many
SELECT platform, channel, SUM(download_count)::bigint as count
FROM download_stats
GROUP BY platform, channel
ORDER BY count DESC
`

type GetTotalDownloadStatsRow struct {
	Platform string `json:"platform"`
	Channel  string `json:"channel"`
	Count    int64  `json:"count"`
}

// Global stats
func (q *Queries) GetTotalDownloadStats(ctx context.Context) ([]GetTotalDownloadStatsRow, error) {
	rows, err := q.db.Query(ctx, getTotalDownloadStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalDownloadStatsRow
	for rows.Next() {
		var i GetTotalDownloadStatsRow
		if err := rows.Scan(&i.Platform, &i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalDownloadsByProject = `-- name: GetTotalDownloadsByProject :many
SELECT update_id, platform, channel, SUM(download_count)::bigint as count
FROM download_stats
WHERE project_id = $1
GROUP BY update_id, platform, channel
ORDER BY count DESC
`

type GetTotalDownloadsByProjectRow struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Platform string      `json:"platform"`
	Channel  string      `json:"channel"`
	Count    int64       `json:"count"`
}

// Project-level stats
func (q *Queries) GetTotalDownloadsByProject(ctx context.Context, projectID pgtype.UUID) ([]GetTotalDownloadsByProjectRow, error) {
	rows, err := q.db.Query(ctx, getTotalDownloadsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalDownloadsByProjectRow
	for rows.Next() {
		var i GetTotalDownloadsByProjectRow
		if err := rows.Scan(
			&i.UpdateID,
			&i.Platform,
			&i.Channel,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalDownloadsByUpdateID = `-- name: GetTotalDownloadsByUpdateID :one
SELECT (
    COALESCE((
        SELECT SUM(download_count)
        FROM download_stats ds
        WHERE ds.update_id = $1
    ), 0)
    +
    (
        SELECT COUNT(*)
        FROM download_events de
        WHERE de.update_id = $1
    )
)::bigint AS count
`

func (q *Queries) GetTotalDownloadsByUpdateID(ctx context.Context, updateID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalDownloadsByUpdateID, updateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
