// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value FROM settings WHERE key = $1
`

type GetSettingRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (GetSettingRow, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const getSettings = `-- name: GetSettings :many
SELECT key, value FROM settings
`

type GetSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSettings(ctx context.Context) ([]GetSettingsRow, error) {
	rows, err := q.db.Query(ctx, getSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSettingsRow
	for rows.Next() {
		var i GetSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :exec
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type UpdateSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.Exec(ctx, updateSetting, arg.Key, arg.Value)
	return err
}
