// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUpdate = `-- name: ActivateUpdate :exec
UPDATE updates
SET is_active = true
WHERE id = $1
`

func (q *Queries) ActivateUpdate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUpdate, id)
	return err
}

const createUpdate = `-- name: CreateUpdate :one
INSERT INTO updates (
    project_id,
    runtime_version,
    channel,
    rollout_percentage,
    platform,
    is_active,
    is_rollback,
    message
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, runtime_version, channel, rollout_percentage, platform, is_active, is_rollback, message, created_at, expo_config
`

type CreateUpdateParams struct {
	ProjectID         pgtype.UUID `json:"project_id"`
	RuntimeVersion    string      `json:"runtime_version"`
	Channel           string      `json:"channel"`
	RolloutPercentage int32       `json:"rollout_percentage"`
	Platform          string      `json:"platform"`
	IsActive          bool        `json:"is_active"`
	IsRollback        bool        `json:"is_rollback"`
	Message           pgtype.Text `json:"message"`
}

func (q *Queries) CreateUpdate(ctx context.Context, arg CreateUpdateParams) (Update, error) {
	row := q.db.QueryRow(ctx, createUpdate,
		arg.ProjectID,
		arg.RuntimeVersion,
		arg.Channel,
		arg.RolloutPercentage,
		arg.Platform,
		arg.IsActive,
		arg.IsRollback,
		arg.Message,
	)
	var i Update
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuntimeVersion,
		&i.Channel,
		&i.RolloutPercentage,
		&i.Platform,
		&i.IsActive,
		&i.IsRollback,
		&i.Message,
		&i.CreatedAt,
		&i.ExpoConfig,
	)
	return i, err
}

const deactivateUpdates = `-- name: DeactivateUpdates :exec
UPDATE updates 
SET is_active = false 
WHERE project_id = $1
AND channel = $2
AND runtime_version = $3
AND platform = $4
AND is_active = true
`

type DeactivateUpdatesParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Channel        string      `json:"channel"`
	RuntimeVersion string      `json:"runtime_version"`
	Platform       string      `json:"platform"`
}

func (q *Queries) DeactivateUpdates(ctx context.Context, arg DeactivateUpdatesParams) error {
	_, err := q.db.Exec(ctx, deactivateUpdates,
		arg.ProjectID,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
	)
	return err
}

const deleteUpdate = `-- name: DeleteUpdate :exec
DELETE FROM updates WHERE id = $1
`

func (q *Queries) DeleteUpdate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUpdate, id)
	return err
}

const getLatestActiveUpdate = `-- name: GetLatestActiveUpdate :one
SELECT id, project_id, runtime_version, channel, rollout_percentage, platform, is_active, is_rollback, message, created_at, expo_config FROM updates 
WHERE is_active = true 
AND project_id = $1
AND platform = $2
AND runtime_version = $3
AND channel = $4
ORDER BY created_at 
DESC LIMIT 1
`

type GetLatestActiveUpdateParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Platform       string      `json:"platform"`
	RuntimeVersion string      `json:"runtime_version"`
	Channel        string      `json:"channel"`
}

func (q *Queries) GetLatestActiveUpdate(ctx context.Context, arg GetLatestActiveUpdateParams) (Update, error) {
	row := q.db.QueryRow(ctx, getLatestActiveUpdate,
		arg.ProjectID,
		arg.Platform,
		arg.RuntimeVersion,
		arg.Channel,
	)
	var i Update
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuntimeVersion,
		&i.Channel,
		&i.RolloutPercentage,
		&i.Platform,
		&i.IsActive,
		&i.IsRollback,
		&i.Message,
		&i.CreatedAt,
		&i.ExpoConfig,
	)
	return i, err
}

const getUpdateByID = `-- name: GetUpdateByID :one
SELECT id, project_id, runtime_version, channel, rollout_percentage, platform, is_active, is_rollback, message, created_at, expo_config FROM updates WHERE id = $1
`

func (q *Queries) GetUpdateByID(ctx context.Context, id pgtype.UUID) (Update, error) {
	row := q.db.QueryRow(ctx, getUpdateByID, id)
	var i Update
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuntimeVersion,
		&i.Channel,
		&i.RolloutPercentage,
		&i.Platform,
		&i.IsActive,
		&i.IsRollback,
		&i.Message,
		&i.CreatedAt,
		&i.ExpoConfig,
	)
	return i, err
}

const getUpdatesCount = `-- name: GetUpdatesCount :one
SELECT COUNT(*) FROM updates
`

func (q *Queries) GetUpdatesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUpdatesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUpdatesCountByProject = `-- name: GetUpdatesCountByProject :one
SELECT COUNT(*) FROM updates 
WHERE project_id = $1
`

func (q *Queries) GetUpdatesCountByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUpdatesCountByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUpdatesByProject = `-- name: ListUpdatesByProject :many
SELECT id, project_id, runtime_version, channel, rollout_percentage, platform, is_active, is_rollback, message, created_at, expo_config FROM updates 
WHERE project_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUpdatesByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListUpdatesByProject(ctx context.Context, arg ListUpdatesByProjectParams) ([]Update, error) {
	rows, err := q.db.Query(ctx, listUpdatesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Update
	for rows.Next() {
		var i Update
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuntimeVersion,
			&i.Channel,
			&i.RolloutPercentage,
			&i.Platform,
			&i.IsActive,
			&i.IsRollback,
			&i.Message,
			&i.CreatedAt,
			&i.ExpoConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdatesPaginated = `-- name: ListUpdatesPaginated :many
SELECT id, project_id, runtime_version, channel, rollout_percentage, platform, is_active, is_rollback, message, created_at, expo_config FROM updates 
ORDER BY created_at DESC 
LIMIT $1 OFFSET $2
`

type ListUpdatesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUpdatesPaginated(ctx context.Context, arg ListUpdatesPaginatedParams) ([]Update, error) {
	rows, err := q.db.Query(ctx, listUpdatesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Update
	for rows.Next() {
		var i Update
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuntimeVersion,
			&i.Channel,
			&i.RolloutPercentage,
			&i.Platform,
			&i.IsActive,
			&i.IsRollback,
			&i.Message,
			&i.CreatedAt,
			&i.ExpoConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpoConfig = `-- name: UpdateExpoConfig :exec
UPDATE updates
SET expo_config = $1
WHERE id = $2
`

type UpdateExpoConfigParams struct {
	ExpoConfig []byte      `json:"expo_config"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateExpoConfig(ctx context.Context, arg UpdateExpoConfigParams) error {
	_, err := q.db.Exec(ctx, updateExpoConfig, arg.ExpoConfig, arg.ID)
	return err
}

const updateRolloutPercentage = `-- name: UpdateRolloutPercentage :exec
UPDATE updates 
SET rollout_percentage = $2 
WHERE id = $1
`

type UpdateRolloutPercentageParams struct {
	ID                pgtype.UUID `json:"id"`
	RolloutPercentage int32       `json:"rollout_percentage"`
}

func (q *Queries) UpdateRolloutPercentage(ctx context.Context, arg UpdateRolloutPercentageParams) error {
	_, err := q.db.Exec(ctx, updateRolloutPercentage, arg.ID, arg.RolloutPercentage)
	return err
}
